apiVersion: v1
kind: Service
metadata:
  name:  content-service
spec:
  selector:
    app:  content-service
  ports:
    - port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
        - name: content-service
          image: scienceporn/content-service
          ports:
            - containerPort: 8082
          imagePullPolicy: Never


