version: '2'
services:
  neo4j:
    hostname: neo4j
    container_name: neo4j
    image: neo4j
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./plugins:/plugins
    networks:
     - scienceporn_network

networks:
  scienceporn_network:
    external: true