server:
  port: 8084

spring:
  profiles: default
  application:
    name: sharing-service
  datasource:
    url: jdbc:mysql://localhost:3306/scienceporn_db?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update

#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


content-service:
  ribbon:
    eureka:
      enabled: false
    ServerListRefreshInterval: 5000
    listOfServers: localhost:8085

auth-server:
  url: http://localhost:8085

management:
  security:
    enabled: false