server:
  port: 8083
  servlet:
    context-path: /share

spring:
  profiles: dev
  application:
    name: sharing-service
  datasource:
    url: jdbc:mysql://localhost:3306/scienceporn_db?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update


kafka:
  topic: contents
  bootstrapAddress: localhost:9094

#logging:
#  level:
#    ROOT: ERROR
#    org.springframework.web: ERROR
#    com.cayan.sharingservice: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: /tmp/science-porn/log/application-sharing-debug.log


user-service:
  ribbon:
    eureka:
      enabled: false
    ServerListRefreshInterval: 5000
    listOfServers: localhost:8084

auth-server:
  url: http://localhost:8081/uaa

management:
  security:
    enabled: false

